name: Funcraft6
version: 1.1
author: glisco03
main: com.glisco.funcraft6.Main
api-version: 1.16
commands:
  dimtp:
    usage: /<command> [target world]
    description: dimtp
  diminfo:
    usage: /<command>
    description: diminfo
  endlock:
    usage: /<command>
    description: endlock
  miniblocks:
    usage: /<command>
    description: miniblocks
  afk:
    usage: /<command>
    description: Controls your AFK status
  fishing:
    usage: /<command>
    description: Controls your fishing status
  freeze:
    usage: /<command>
    description: Freezes Players
  spectate:
    usage: /<command>
    description: Lets you use a limited spectator view
  public:
    usage: /<command>
    description: Lets you make signs public
  private:
    usage: /<command>
    description: Lets you make signs private
  rulez:
    usage: /<command>
    description: Shows the rulez
  getitem:
    usage: /<command>
    description: getitem
  spawn:
    usage: /<command>
    description: Used to go to spawn and back
  arms:
    usage: /<command>
    description: Used to enable/disable the arms of armor stands
  small:
    usage: /<command>
    description: Used to control the size of armor stands
  isneak:
    usage: /<command>
    description: Used to control item pickup
  updateitem:
    usage: /<command>
    description: Used to update items to new id system
  chatpos:
    usage: /<command>
    description: Used to put your current position in chat
  invsee:
    usage: /<command>
    description: invsee
  dragondelete:
    usage: /<command>
    description: invsee